version: "3.3"

services:
  shard1:
    image: mariadb:10.5
    container_name: shard1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - maxscale_shard_net

  shard2:
    image: mariadb:10.5
    container_name: shard2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - maxscale_shard_net

  maxscale:
    build: .
    container_name: maxscale
    ports:
      - "4006:4006"
    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf
      - ./maxscale/maxscale.cnf.d:/etc/maxscale.cnf.d
    depends_on:
      - shard1
      - shard2
    restart: unless-stopped
    networks:
      - maxscale_shard_net

networks:
  maxscale_shard_net:
    driver: bridge
